### ISSUE TITLE
authors, and author order

### ISSUE THREAD

**Issue by HWRix** [HWRix/Haloprofile#5]
after next iteration, we should circulate the draft to all authors so far.
We should probably include Heather Morrison.

**Comment by xuexx** [comment]
Ok, I will add Heather. I have revised the plots and cleaned up the text, but have not finished the table. Tomorrow I will move to Beijing, taking along with my Son. I will look after him by myself. :-)  I plan to send you the revised draft on Jan 5th.

**Comment by HWRix** [comment]
Author list now looks good to me.
